//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Draws')
export class DrawsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('date', { nullable: true })
  DrawTime: Date;

  @Column('integer', { nullable: true })
  WinningNumber: number;

  @Column('text', { nullable: true })
  WinningColour: string;
}
