//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Tickets')
export class TicketsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  TicketID: number;

  @Column('integer', { nullable: true })
  PlayersNumberChoice: number;

  @Column('text', { nullable: true })
  PlayersColourChoice: string;

  @Column('integer', { nullable: true })
  AmountBet: number;
}
