//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Wingo')
export class WingoEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  GameName: string;

  @Column('integer', { nullable: true })
  DrawFrequency: number;

  @Column('text', { nullable: true })
  ColourPrediction: string;

  @Column('text', { nullable: true })
  BigSmall: string;

  @Column('text', { nullable: true })
  BettingOptions: string;
}
