//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Wingo: [
      {
        GameName: 'GameName 1',
        DrawFrequency: 1,
        ColourPrediction: 'ColourPrediction 1',
        BigSmall: 'BigSmall 1',
        BettingOptions: 'BettingOptions 1',
        id: 10,
      },
      {
        GameName: 'GameName 2',
        DrawFrequency: 2,
        ColourPrediction: 'ColourPrediction 2',
        BigSmall: 'BigSmall 2',
        BettingOptions: 'BettingOptions 2',
        id: 64,
      },
      {
        GameName: 'GameName 3',
        DrawFrequency: 3,
        ColourPrediction: 'ColourPrediction 3',
        BigSmall: 'BigSmall 3',
        BettingOptions: 'BettingOptions 3',
        id: 46,
      },
      {
        GameName: 'GameName 4',
        DrawFrequency: 4,
        ColourPrediction: 'ColourPrediction 4',
        BigSmall: 'BigSmall 4',
        BettingOptions: 'BettingOptions 4',
        id: 90,
      },
      {
        GameName: 'GameName 5',
        DrawFrequency: 5,
        ColourPrediction: 'ColourPrediction 5',
        BigSmall: 'BigSmall 5',
        BettingOptions: 'BettingOptions 5',
        id: 72,
      },
    ],
    Draws: [
      {
        DrawTime: '2025-03-22T20:00:36.794Z',
        WinningNumber: 1,
        WinningColour: 'WinningColour 1',
        id: 33,
      },
      {
        DrawTime: '2023-05-23T15:55:07.989Z',
        WinningNumber: 2,
        WinningColour: 'WinningColour 2',
        id: 33,
      },
      {
        DrawTime: '2024-06-15T00:27:30.039Z',
        WinningNumber: 3,
        WinningColour: 'WinningColour 3',
        id: 27,
      },
      {
        DrawTime: '2024-02-11T06:27:16.915Z',
        WinningNumber: 4,
        WinningColour: 'WinningColour 4',
        id: 7,
      },
      {
        DrawTime: '2024-03-20T22:58:09.650Z',
        WinningNumber: 5,
        WinningColour: 'WinningColour 5',
        id: 24,
      },
    ],
    Tickets: [
      {
        TicketID: 1,
        PlayersNumberChoice: 1,
        PlayersColourChoice: 'PlayersColourChoice 1',
        AmountBet: 1,
        id: 81,
      },
      {
        TicketID: 2,
        PlayersNumberChoice: 2,
        PlayersColourChoice: 'PlayersColourChoice 2',
        AmountBet: 2,
        id: 6,
      },
      {
        TicketID: 3,
        PlayersNumberChoice: 3,
        PlayersColourChoice: 'PlayersColourChoice 3',
        AmountBet: 3,
        id: 0,
      },
      {
        TicketID: 4,
        PlayersNumberChoice: 4,
        PlayersColourChoice: 'PlayersColourChoice 4',
        AmountBet: 4,
        id: 5,
      },
      {
        TicketID: 5,
        PlayersNumberChoice: 5,
        PlayersColourChoice: 'PlayersColourChoice 5',
        AmountBet: 5,
        id: 94,
      },
    ],
    Users: [
      { UserName: 'UserName 1', Email: 'Email 1', Balance: 0.44, id: 13 },
      { UserName: 'UserName 2', Email: 'Email 2', Balance: 0.45, id: 55 },
      { UserName: 'UserName 3', Email: 'Email 3', Balance: 0.67, id: 17 },
      { UserName: 'UserName 4', Email: 'Email 4', Balance: 0.07, id: 93 },
      { UserName: 'UserName 5', Email: 'Email 5', Balance: 0.66, id: 53 },
    ],
  },
};
export default data;
